### ISSUE TITLE
Is TestLogger missing

### ISSUE THREAD

**Issue by remicollet** [jbboehr/php-psr#57]
See https://github.com/php-fig/log/pull/57

IIUC, this is not part of the PSR-3, but provided by the psr/log pure-PHP library

**Comment by jbboehr** [comment]
Yeah, it's definitely not yet implemented. The extension [was written against](https://github.com/jbboehr/php-psr/blob/master/psr_log.h#L8) v1.0.0 of psr/log (IIRC the 1.0.x releases since then have been documentation-only). 

I also did not implement [LoggerInterfaceTest](https://github.com/php-fig/log/blob/master/Psr/Log/Test/LoggerInterfaceTest.php) as it extends a userland class from phpunit, and, while I wouldn't be surprised if it was possible, I'm not sure if an internal class extending a userland class is a good idea or worth the trouble, although I would be happy to hear someone disagree.

I think that, on the above precedent, and that most likely TestLogger will only be used in userland test code and not in extensions, which this extension was intended to serve, that we should *not* implement the class and document that users should install psr/log if they need the test-related classes.

cc @sergeyklay

**Comment by sergeyklay** [comment]
In general I agree with @jbboehr. In any case `TestLogger` was[ implemented in the `psr/log` v1.1.0](https://github.com/php-fig/log/releases/tag/1.1.0). So users can specify desired version as well as their expectations in the `composer.json`. In other words, if users installs the `php-psr` extension, then they will expect functionality appropriate with `php-psr`'s change log.

@Jean85 Is there any chance to move `TestLogger` outside of PSR Log API, for example to the separated (and [suggested in the `composer.json`](https://getcomposer.org/doc/04-schema.md#suggest)) library?

**Comment by Jean85** [comment]
Moving the testlogger outside now, after a release, would break BC; not possible without bumping `psr/log` to 2.0, which would not solve your issue.

BTW, it's not part of the PSR, it's just an utility class useful for tests; I don't know if you should implement that.
