### ISSUE TITLE
1.0?

### ISSUE THREAD

**Issue by dzuelke** [jbboehr/php-psr#75]
May I propose bumping the next version (or making a release without changes) to 1.0.0?

I'm asking this mainly due to SemVer's and Composers well-defined differences between pre-1.0 and all other version strings for comparison purposes (as `^0.7.0` means `>= 0.7.0 <0.8.0`), so it's likely to make life a bit easier long-term for the interoperability of components that want to rely on the extension.

**Comment by jbboehr** [comment]
Such is the fate of all my software: the API stabilizes in 0.x but then no further release breaks B/C or feels significant enough for a major version bump. :)

IIRC (and my memory may be wrong) it sounded like PHP-FIG was likely going to introduce new PSRs instead of releasing new major versions of existing PSRs, so there may never be a B/C break.

I suppose we can just tag a new release now as 1.0 if that is the proper thing to do, although there's been no code changes since the latest 0.7 tag.

cc @sergeyklay @flyinghail

**Comment by sergeyklay** [comment]
I'm OK with releasing 1.0.0. Thank you for the ping

**Comment by flyinghail** [comment]
I'm OK, too. Thank you for the ping.

**Comment by dzuelke** [comment]
Yeah for published PSRs, there will never be a change. Everything works only through additions.

That means your next release could be 1.0.0, and then with each PSR that gets added, you bump to 1.1.0, 1.2.0, and so forth, without ever reaching 2.0.

The benefit for packages that want to depend on your extension is that they can just express `^1.4.0` or whatever minimum PSR they need, without having to worry about the 0.x SemVer differences (right now, a package would have to declare `>=0.7.0 <=2.0.0` or something like that).

**Comment by jbboehr** [comment]
Tagged 07051167a95ffb98ac976701b600bb6b9de28526 as v1.0.0
